apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-learning-app-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tafukagawa/K8s-learn.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-learning-app-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
