apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  namespace: k8s-learning-app-api
  labels:
    app: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong
          image: kong:3.7
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/declarative/kong.yml
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000"
            - name: KONG_STATUS_LISTEN
              value: "0.0.0.0:8100"
          ports:
            - containerPort: 8000
              name: proxy
            - containerPort: 8100
              name: status
          volumeMounts:
            - name: kong-config
              mountPath: /kong/declarative
          readinessProbe:
            httpGet:
              path: /status
              port: 8100
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: 8100
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: kong-config
          configMap:
            name: kong-declarative-config
