apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: progress-data
  namespace: k8s-learning-app-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
